default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username:  <%= ENV['SHOWTIME_APIS_DATABASE_PASSWORD'] || 'postgres' %>
  password:  <%= ENV['SHOWTIME_APIS_DATABASE_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: showtime_apis_development
test:
  <<: *default
  database: showtime_apis_test
production:
  <<: *default
  database: showtime_apis_production
  username: showtime_apis
  password: <%= ENV['SHOWTIME_APIS_DATABASE_PASSWORD'] %>
